FROM python:3.14-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY dependency.py .

EXPOSE 8001

CMD ["uvicorn", "dependency:app", "--host", "0.0.0.0", "--port", "8001"]
